apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-search-xls
  namespace: {{namespace}}
spec:
  ## run every 5 min (once at 23:55 -> "55 23 * * *")
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 1200
          restartPolicy: Never
          containers:
            - name: import-search-xls
              image: 066879069397.dkr.ecr.us-east-1.amazonaws.com/zoomd-etlservices:{{version}}
              command: ["/bin/bash", "-c", "node src/jobs/importSearchXLS"]
              envFrom:
                - secretRef:
                    name: etlservices-secret
                - configMapRef:
                    name: etlservices-config
              env:
                - name: optional_var_name
                  value: some value
      backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

