apiVersion: v1
kind: Service
metadata:
  name: ts-node-starter-service
  namespace: {{namespace}}
spec:
  type: NodePort
  selector:
    app: ts-node-starter
  ports:
    - port: 8104
      targetPort: 8104
      protocol: TCP