apiVersion: v1
kind: Service
metadata:
  name: etlservices-service
  namespace: {{namespace}}
spec:
  type: NodePort
  selector:
    app: etlservices
  ports:
    - port: 8104
      targetPort: 8104
      protocol: TCP